<?php

//define('DB_HOST','localhost');
define('DB_HOST','171.100.56.194');
//define('DB_HOST','192.168.88.40');
//define('DB_HOST','192.168.88.7');

define('DB_PORT','3307');
define('DB_USER','myadmin');
define('DB_PASS','myadmin');
define('DB_NAME','sac_lotto');

//Hosting Z.com

/*
define('DB_HOST','118.27.130.235');
define('DB_PORT','3306');
define('DB_USER','zlpnppsz_admin');
define('DB_PASS','Sac168168');
define('DB_NAME','zlpnppsz_lotto');
*/

