<?php

//define('DB_HOST','localhost');
//NXFMMmRseFY0WjhpWkVnMDZIRWRUQT09OjrmaF1jNV/ZW26tXcrlpT+g

//define('DB_HOST','171.100.56.194');
//define('DB_HOST','192.168.88.40');
//define('DB_HOST','192.168.88.7');
//define('DB_PORT','3307');

define('DB_HOST','S1k5aHVNTzdhd250amd2ZXpXbnh0Zz09OjqLJ4TXuGCgYBxaBuaMMrHF');
//define('DB_PORT','3307');
define('DB_PORT','OU51QkcvVW83YlI5MkVMeloyTUxLQT09Ojo1EYxbdBOQLzEzkeYqngWm');
define('DB_USER','ZnV5SHNLN2tpSVhBUTZEVXBkRHJrZz09OjqvlWYmNy6SZVd1ivYI2PhY');
define('DB_PASS','ZnV5SHNLN2tpSVhBUTZEVXBkRHJrZz09OjqvlWYmNy6SZVd1ivYI2PhY');
define('DB_NAME','bVlpQlM3b1llYW9CaTg5cytVSlZDZz09Ojq992dVq9HdNbLaIKXbCIJx');

//Hosting Z.com

/*
define('DB_HOST','118.27.130.235');
define('DB_PORT','3306');
define('DB_USER','zlpnppsz_admin');
define('DB_PASS','Sac168168');
define('DB_NAME','zlpnppsz_lotto');
*/